import Script from 'next/script'
import { Inter } from "next/font/google";
import "./globals.css";
import Header from "./components/Header";
import Link from 'next/link';

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
      <Link href="https://cdnjs.cloudflare.com/ajax/libs/flowbite/2.2.1/flowbite.min.css"  rel="stylesheet" />
        <Header/>
        {children}
       
        </body>
    </html>
  );
}
